listen_addresses: "0.0.0.0:3000"
worker_processes: 32
cache_size_mb: 512
postgres:
  connection_string: "postgresql://postgres:123456@localhost:5432/Geometry"
  pool_size: 20
  auto_publish:
    tables:
      from_schemas: ["public"]
      id_regex: "^vector_.*"  # 只发布符合规则的表