listen_addresses: 0.0.0.0:3000
worker_processes: 32
cache_size_mb: 5120
postgres:
  connection_string: postgresql://postgres:123456@localhost:5432/Geometry
  pool_size: 20
  auto_publish:
    tables:
      from_schemas: ["public"]
      id_regex: "^vector_.*"  # 只发布符合规则的表
mbtiles:
  # 指定MBTiles文件所在目录
  dir: "G:\\code\\shpservice\\FilesData\\mbtiles"
  # 可选：是否自动发布该目录下的所有MBTiles文件
  auto_publish: true
  # 可选：指定文件名匹配模式（使用glob模式）
  file_regex: ".*\\.mbtiles$"  # 匹配所有.mbtiles文件